-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_user_id VARCHAR(64) UNIQUE NOT NULL,
    name TEXT,
    picture TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Characters table
CREATE TABLE IF NOT EXISTS characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    job TEXT,
    level INTEGER,
    game_id TEXT,
    note TEXT,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Raids table
CREATE TABLE IF NOT EXISTS raids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    boss TEXT,
    start_time TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Raid signups table
CREATE TABLE IF NOT EXISTS raid_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raid_id BIGINT NOT NULL REFERENCES raids(id) ON DELETE CASCADE,
    character_id BIGINT NOT NULL REFERENCES characters(id),
    status TEXT DEFAULT 'confirmed',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(raid_id, character_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_characters_user_id ON characters(user_id);
CREATE INDEX IF NOT EXISTS idx_raids_start_time ON raids(start_time);
CREATE INDEX IF NOT EXISTS idx_raid_signups_raid_id ON raid_signups(raid_id);
CREATE INDEX IF NOT EXISTS idx_raid_signups_character_id ON raid_signups(character_id);
